name: Simple CD

on:
  push:
    branches:
      - master

jobs:
  run-ci:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run lint
    - run: npm run predeploy
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
       ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
       FOLDER: build_gh_pages
       BRANCH: gh-pages
